//////////////
// ACTION TYPE CONSTANTS
//////////////

// USER
export const LOGIN_USER = 'LOGIN_USER'

// USER EXERCISES 
export const GET_ALL_USER_EXERCISES_REQUEST = 'GET_ALL_USER_EXERCISES_REQUEST'
export const GET_ALL_USER_EXERCISES_SUCCESS = 'GET_ALL_USER_EXERCISES_SUCCESS'
export const GET_ALL_USER_EXERCISES_FAILURE = 'GET_ALL_USER_EXERCISES_FAILURE'

export const PUT_NEW_USER_EXERCISE_REQUEST = 'PUT_NEW_USER_EXERCISE_REQUEST'
export const PUT_NEW_USER_EXERCISE_SUCCESS = 'PUT_NEW_USER_EXERCISE_SUCCESS'
export const PUT_NEW_USER_EXERCISE_FAILURE = 'PUT_NEW_USER_EXERCISE_FAILURE'
export const INVALIDATE_USER_EXERCISES = 'INVALIDATE_USER_EXERCISES'

// USER WORKOUTS 
export const GET_ALL_USER_WORKOUTS_REQUEST = 'GET_ALL_USER_WORKOUTS_REQUEST'
export const GET_ALL_USER_WORKOUTS_SUCCESS = 'GET_ALL_USER_WORKOUTS_SUCCESS'
export const GET_ALL_USER_WORKOUTS_FAILURE = 'GET_ALL_USER_WORKOUTS_FAILURE'

export const PUT_NEW_USER_WORKOUT_REQUEST = 'PUT_NEW_USER_WORKOUT_REQUEST'
export const PUT_NEW_USER_WORKOUT_SUCCESS = 'PUT_NEW_USER_WORKOUT_SUCCESS'
export const PUT_NEW_USER_WORKOUT_FAILURE = 'PUT_NEW_USER_WORKOUT_FAILURE'

// USER TEMPLATES
export const GET_ALL_USER_TEMPLATES_REQUEST = 'GET_ALL_USER_TEMPLATES_REQUEST'
export const GET_ALL_USER_TEMPLATES_SUCCESS = 'GET_ALL_USER_TEMPLATES_SUCCESS'
export const GET_ALL_USER_TEMPLATES_FAILURE = 'GET_ALL_USER_TEMPLATES_FAILURE'

export const PUT_NEW_USER_TEMPLATE_REQUEST = 'PUT_NEW_USER_TEMPLATE_REQUEST'
export const PUT_NEW_USER_TEMPLATE_SUCCESS = 'PUT_NEW_USER_TEMPLATE_SUCCESS'
export const PUT_NEW_USER_TEMPLATE_FAILURE = 'PUT_NEW_USER_TEMPLATE_FAILURE'

// USER PROGRAMS
export const GET_ALL_USER_PROGRAMS_REQUEST = 'GET_ALL_USER_PROGRAMS_REQUEST'
export const GET_ALL_USER_PROGRAMS_SUCCESS = 'GET_ALL_USER_PROGRAMS_SUCCESS'
export const GET_ALL_USER_PROGRAMS_FAILURE = 'GET_ALL_USER_PROGRAMS_FAILURE'

export const PUT_NEW_USER_PROGRAM_REQUEST = 'PUT_NEW_USER_PROGRAM_REQUEST'
export const PUT_NEW_USER_PROGRAM_SUCCESS = 'PUT_NEW_USER_PROGRAM_SUCCESS'
export const PUT_NEW_USER_PROGRAM_FAILURE = 'PUT_NEW_USER_PROGRAM_FAILURE'

export const UPDATE_USER_PROGRAM_REQUEST = 'UPDATE_USER_PROGRAM_REQUEST'
export const UPDATE_USER_PROGRAM_SUCCESS = 'UPDATE_USER_PROGRAM_SUCCESS'
export const UPDATE_USER_PROGRAM_FAILURE = 'UPDATE_USER_PROGRAM_FAILURE'

// ALL EXERCISES 
export const SEARCH_ALL_EXERCISES_SUCCESS = 'SEARCH_ALL_EXERCISES_SUCCESS'
export const SEARCH_ALL_EXERCISES_REQUEST= 'SEARCH_ALL_EXERCISES_REQUEST'
export const SEARCH_ALL_EXERCISES_FAILURE = 'SEARCH_ALL_EXERCISES_FAILURE'

export const PUT_NEW_EXERCISE_REQUEST = 'PUT_NEW_EXERCISE_REQUEST'
export const PUT_NEW_EXERCISE_SUCCESS = 'PUT_NEW_EXERCISE_SUCCESS'
export const PUT_NEW_EXERCISE_FAILURE = 'PUT_NEW_EXERCISE_FAILURE'

// TEMPLATE
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const ADD_SET = 'ADD_SET'

// WORKOUT
export const CREATE_WORKOUT_FROM_TEMPLATE = 'CREATE_WORKOUT_FROM_TEMPLATE'
export const ADD_SET_REPS = 'ADD_SET_REPS'

// PROGRAMS 
export const CREATE_PROGRAM = 'CREATE_PROGRAM'
export const EDIT_PROGRAM = 'EDIT_PROGRAM'
export const USE_PROGRAM = 'USE_PROGRAM'
export const SAVE_PROGRAM = 'SAVE_PROGRAM'
export const ADD_TEMPLATE = 'ADD_TEMPLATE'

// DELOAD
export const CREATE_DELOAD_FROM_TEMPLATE = 'CREATE_DELOAD_FROM_TEMPLATE'

// RESULTS
export const SET_WORKOUT_RESULTS = 'SET_WORKOUT_RESULTS'

// PERFORMANCE
export const SET_PERFORMANCE_EXERCISE = 'SET_PERFORMANCE_EXERCISE'