// export const ADD_TODO = 'ADD_TODO'
export const LOGIN_USER = 'LOGIN_USER'
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE'
export const SAVE_TEMPLATE = 'SAVE_TEMPLATE'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const ADD_SET = 'ADD_SET'
export const CREATE_WORKOUT_FROM_TEMPLATE = 'CREATE_WORKOUT_FROM_TEMPLATE'
export const ADD_SET_REPS = 'ADD_SET_REPS'

// export const FETCH_USER_EXERCISES_REQUEST = 'FETCH_USER_EXERCISES_REQUEST'
// export const FETCH_USER_EXERCISES_FAILURE = 'FETCH_USER_EXERCISES_FAILURE'
// export const FETCH_USER_EXERCISES_SUCCESS = 'FETCH_USER_EXERCISES_SUCCESS'

export const REQUEST_USER_EXERCISES = 'REQUEST_USER_EXERCISES'
export const RECEIVE_USER_EXERCISES = 'RECEIVE_USER_EXERCISES'
export const INVALIDATE_USER_EXERCISES = 'INVALIDATE_USER_EXERCISES'
export const ADD_USER_EXERCISE = 'ADD_USER_EXERCISE'

export const REQUEST_DB_EXERCISES = 'REQUEST_DB_EXERCISES'
export const RECEIVE_DB_EXERCISES = 'RECEIVE_DB_EXERCISES'
export const ADDING_DB_EXERCISE = 'ADDING_DB_EXERCISE'
export const ADDED_DB_EXERCISE = 'ADDED_DB_EXERCISE'

export const SET_WORKOUT_RESULTS = 'SET_WORKOUT_RESULTS'; 

export const RECEIVE_ALL_USER_WORKOUTS = 'RECEIVE_ALL_USER_WORKOUTS'
export const REQUEST_ALL_USER_WORKOUTS = 'REQUEST_ALL_USER_WORKOUTS'
export const SAVE_WORKOUT = 'SAVE_WORKOUT'
// Tests for asynchronous fetch
// export const REQUEST_POSTS = 'REQUEST_POSTS'
// export const RECEIVE_POSTS = 'RECEIVE_POSTS'
// export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
// export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'